import tkinter as tk
class MyCalculator:
    def __init__(self):
        self.root = tk.Tk()
        self.root.geometry("550x650")
        self.root.resizable(0, 0)
        self.root.title("Calculator Pro X +++")
        self.root.option_add("*Font", "ComicSansMS 25")

        self.label = tk.Label(self.root, text="Calculator Pro X +++", font=('Comic Sans MS', 40))
        self.label.pack()
        self.label = tk.Label(self.root, text="                    ", font=('Comic Sans MS', 40),bg="yellow")
        self.label.place(x=105,y=70)
        self.button = tk.Button(self.root, text="CE", width=3, height=1)
        self.button.place(x=85, y=150)
        self.button = tk.Button(self.root, text="()", width=3, height=1)
        self.button.place(x=185, y=150)
        self.button = tk.Button(self.root, text="%", width=3, height=1)
        self.button.place(x=285, y=150)
        self.button = tk.Button(self.root, text="/", width=3, height=1)
        self.button.place(x=385, y=150)
        self.button = tk.Button(self.root, text="x", width=3, height=1)
        self.button.place(x=385, y=240)
        self.button = tk.Button(self.root, text="-", width=3, height=1)
        self.button.place(x=385, y=340)
        self.button = tk.Button(self.root, text="+", width=3, height=1)
        self.button.place(x=385, y=440)
        self.button = tk.Button(self.root, text="7", width=3, height=1)
        self.button.place(x=85, y=240)
        self.button = tk.Button(self.root, text="8", width=3, height=1)
        self.button.place(x=185, y=240)
        self.button = tk.Button(self.root, text="9", width=3, height=1)
        self.button.place(x=285, y=240)
        self.button = tk.Button(self.root, text="4", width=3, height=1)
        self.button.place(x=85, y=340)
        self.button = tk.Button(self.root, text="5", width=3, height=1)
        self.button.place(x=185, y=340)
        self.button = tk.Button(self.root, text="6", width=3, height=1)
        self.button.place(x=285, y=340)
        self.button = tk.Button(self.root, text="1", width=3, height=1)
        self.button.place(x=85, y=440)
        self.button = tk.Button(self.root, text="2", width=3, height=1)
        self.button.place(x=185, y=440)
        self.button = tk.Button(self.root, text="3", width=3, height=1)
        self.button.place(x=285, y=440)
        self.button = tk.Button(self.root, text="+/-", width=3, height=1)
        self.button.place(x=85, y=540)
        self.button = tk.Button(self.root, text="0", width=3, height=1)
        self.button.place(x=185, y=540)
        self.button = tk.Button(self.root, text=".", width=3, height=1)
        self.button.place(x=285, y=540)
        self.button = tk.Button(self.root, text="=", width=3, height=1)
        self.button.place(x=385, y=540)
      


        self.root.mainloop()


MyCalculator()